In [6]:
#1.e
import torch

def fsum(theta,x,k):
  t=0
  p=x-theta
  #for i in range(1,k+1):
  t=t+torch.exp(k*(p**k))

  #print(t)
  t.backward()
    
  return t#torch.log(t)

def fmul(theta,x,k):
  s=1
  #for i in range(1,k+1):
    
  s=s*torch.exp(k*(x-theta)**k)
  #print(s,i*((x-theta)**i))
  #print(s)
  s.backward()
  
  return s#torch.log(t)

k=torch.tensor(2)
x=torch.tensor(1.5,requires_grad=True )
theta=torch.tensor(1 )
y=torch.tensor(0)
z=torch.tensor(0)
y=fsum(theta,x,k)
#y.backward(retain_graph=True)
#print(y)
y=torch.log(y)
#y.backward()
print(x.grad)
xx=torch.tensor(1.5,requires_grad=True )
z=fmul(theta,xx,k)
z=torch.log(z)
print(x.grad)



derivative_result=0


for i in range(1,k+1):
  derivative_result+=torch.mul(i**2,(x-theta)**(i-1))

print(derivative_result)


tensor(3.2974)
tensor(3.2974)
tensor(3., grad_fn=<AddBackward0>)


In [7]:
#1.h

import torch

#Given Matrix A
A=torch.tensor([[5.,10.],[-2.,0.],[1.,-1.]])

#Matrix A Transpose(AT)
ATran=torch.transpose(A,0,1)
print('Matrix A:\n',A,'\nMatrix A Transpose:\n',ATran)

#A*AT & AT*A
Res1_Matrix=torch.matmul(A,ATran)
Res2_Matrix=torch.matmul(ATran,A)
print('A * AT:\n',Res1_Matrix,'\nAT * A:\n',Res2_Matrix)

#Determinant of A*AT and AT*A
Det1=(Res1_Matrix[0][0] * (Res1_Matrix[1][1]*Res1_Matrix[2][2] - Res1_Matrix[2][1]*Res1_Matrix[1][2])
    -Res1_Matrix[1][0] * (Res1_Matrix[0][1]*Res1_Matrix[2][2] - Res1_Matrix[2][1]*Res1_Matrix[0][2])
    +Res1_Matrix[2][0] * (Res1_Matrix[0][1]*Res1_Matrix[1][2] - Res1_Matrix[1][1]*Res1_Matrix[0][2]))#.type(torch.FloatTensor))
Det2=torch.det(Res2_Matrix)#.type(torch.FloatTensor))
print('\nDet1:',Det1,'\nDet2:',Det2)

#Trace of A*AT and AT*A
Trace_Res1=sum(torch.diag(Res1_Matrix,diagonal=0))
Trace_Res2=sum(torch.diag(Res2_Matrix,diagonal=0))
print('\nTrace (A AT):',Trace_Res1,'\nTrace (AT A):',Trace_Res1)

#Forbenius Norm
print('\ninbuilt Method frobenius Square:',torch.frobenius_norm(A)**2)
x,y=A.shape
frob1_Square=0
for i in range(x):
  for j in range(y):
    frob1_Square+=A[i][j]*A[i][j]

print('frobenius_norm_Square:',frob1_Square)
print('\nfrobenius_norm is equal to square root of Trace(A AT)')


Matrix A:
 tensor([[ 5., 10.],
        [-2.,  0.],
        [ 1., -1.]]) 
Matrix A Transpose:
 tensor([[ 5., -2.,  1.],
        [10.,  0., -1.]])
A * AT:
 tensor([[125., -10.,  -5.],
        [-10.,   4.,  -2.],
        [ -5.,  -2.,   2.]]) 
AT * A:
 tensor([[ 30.,  49.],
        [ 49., 101.]])

Det1: tensor(0.) 
Det2: tensor(629.)

Trace (A AT): tensor(131.) 
Trace (AT A): tensor(131.)

inbuilt Method frobenius Square: tensor(131.)
frobenius_norm_Square: tensor(131.)

frobenius_norm is equal to square root of Trace(A AT)


In [8]:
#4.b
import torch
import torch.nn as nn
### This class is NOT a Pytorch layer. You'll need to turn it into one.
class Eqn1(nn.Module):
  
  def __init__(self, dim=2, omega=None):
    """
    * omega is a vector of size 2
    """
    super(Eqn1, self).__init__()
    ### some initialization is missing....
    if omega is not None:
      self.omega = omega
    else:
      self.omega = torch.zeros(size=(dim,))

  ### continue implementing this class, in order to turn it into a 
  ### Pytorch layer
  def forward(self, Ys):
    """
    Ys is a binary vector of size N.

    This function computes Eqn (1) on the provides `Ys`, according to the
    current `omega` of the model.
    """
    compute_value=0
    for i in range(len(Ys)):
     compute_value=compute_value+(-1)*omega[Ys[i]]+torch.log(torch.exp(omega[0])+torch.exp(omega[1]))
    #compute_value=compute_value+(-1)*omega[Ys[N]]+torch.log(torch.exp(omega[0])+torch.exp(omega[1]))
    print(compute_value)
    return compute_value
    #pass

N=5
Ys=torch.tensor([1,0,0,1,1])
omega=torch.tensor([0.5,-0.2] )
pyLayer=Eqn1(dim=2,omega=omega)
pyout=pyLayer(Ys)
#pyLayer=Eqn1(torch.tensor([1,0,0,1,1]))
#pyLayer=Eqn1(dim=2,omega=torch.tensor([0.5,-0.2] ))
#pyLayer.forward(torch.tensor([1,0,0,1,1]))


N=8
Ys=torch.tensor([1,0,0,1,1,0,1,1])
omega=torch.tensor([0.5,-0.5] )
pyLayer=Eqn1(dim=2,omega=omega)
pyout=pyLayer(Ys)
#pyLayer=Eqn1(omega=torch.tensor([0.5,-0.5]))
#pyLayer.forward([1,0,0,1,1,0,1,1])

N=int(input("Enter N"))
Ys=torch.tensor(list(map(int,input("Enter n elements").split()[:N])))
omega=torch.tensor([0.5,-0.5] )
pyLayer=Eqn1(dim=2,omega=omega)
pyout=pyLayer(Ys)
print(Ys)

tensor(4.1159)
tensor(7.5061)
Enter N5
Enter n elements0 1 0 1 1
tensor(4.5663)
tensor([0, 1, 0, 1, 1])


In [9]:
#4.c.ii
import torch

def fw0(w,y,n):
  t=0
  s=0
  #t=t+(-w[y[n]])+torch.log(torch.exp(w0)+torch.exp(w1))
  t=t+((n-2)*-w1)+(n-2)*torch.log(torch.exp(w0)+torch.exp(w1))
  s=s+((n-3)*-w0)+(n-3)*torch.log(torch.exp(w0)+torch.exp(w1))
  l=s+t
  #t.backward()
  l.backward()
    
  return l

n=torch.tensor(5)
#w=torch.tensor([0.5,-0.2] )
w0=torch.tensor(0.5,requires_grad=True )
w1=torch.tensor(-0.2,requires_grad=True )
w=torch.tensor([w0,w1] )
y=torch.tensor([300,1,0,0,1,1])
#z=torch.tensor(0)
z=fw0(w,y,n)

print(w0.grad)
print(w1.grad)

tensor(1.3409)
tensor(-1.3409)


In [10]:
#4.D
import torch

def fw0(w,y,n):
  t=0
  s=0
  #t=t+(-w[y[n]])+torch.log(torch.exp(w0)+torch.exp(w1))
  t=t+((n-2)*-w1)+(n-2)*torch.log(torch.exp(w0)+torch.exp(w1))
  s=s+((n-3)*-w0)+(n-3)*torch.log(torch.exp(w0)+torch.exp(w1))
  l=s+t
  #t.backward()
  l.backward()
    
  return l


n=torch.tensor(5)
#eq=((n-3)*-w0)+(n)*torch.log(torch.exp(w0)+torch.exp(w1))+((n-2)*-w1)

#w=torch.tensor([0.5,-0.2] )
w0=torch.tensor(0.0,requires_grad=True )
w1=torch.tensor(0.0,requires_grad=True )
w=torch.tensor([w0,w1] )
y=torch.tensor([300,1,0,0,1,1])
#z=torch.tensor(0)
z=fw0(w,y,n)
print(w0.grad)
print(w1.grad)



tensor(0.5000)
tensor(-0.5000)
